openapi: 3.0.1
info:
  contact: {}
  title: Masters way notification API
  version: "1.0"
servers:
- url: /notification
paths:
  /dev/resetDb:
    get:
      description: resets db
      responses:
        "204":
          content: {}
          description: No Content
      summary: resets db
      tags:
      - dev
  /enabledNotifications:
    get:
      operationId: get-enabledNotification-list
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/schemas.GetEnabledNotificationListResponse'
          description: OK
      summary: Get enabledNotification list by user id
      tags:
      - enabledNotification
    post:
      operationId: create-enabledNotification
      responses:
        "204":
          content: {}
          description: No Content
      summary: Create a new enabledNotifications
      tags:
      - enabledNotification
  /enabledNotifications/{enabledNotificationId}:
    patch:
      operationId: update-enabledNotification
      parameters:
      - description: notification id
        in: path
        name: enabledNotificationId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/schemas.UpdateEnabledNotificationPayload'
        description: query params
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/schemas.EnabledNotificationResponse'
          description: OK
      summary: Update enabledNotification by id
      tags:
      - enabledNotification
      x-codegen-request-body-name: request
  /notifications:
    get:
      operationId: get-notification-list
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/schemas.GetNotificationListResponse'
          description: OK
      summary: Get notification list by user id
      tags:
      - notification
    post:
      operationId: create-notification
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/schemas.CreateNotificationPayload'
        description: query params
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/schemas.NotificationResponse'
          description: OK
      summary: Create a new notification
      tags:
      - notification
      x-codegen-request-body-name: request
  /notifications/{notificationId}:
    patch:
      operationId: update-notification
      parameters:
      - description: notification id
        in: path
        name: notificationId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/schemas.UpdateNotificationPayload'
        description: query params
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/schemas.NotificationResponse'
          description: OK
      summary: Update notification by id
      tags:
      - notification
      x-codegen-request-body-name: request
components:
  schemas:
    schemas.CreateNotificationPayload:
      properties:
        description:
          type: string
        nature:
          type: string
        url:
          type: string
      required:
      - description
      - nature
      - url
      type: object
    schemas.EnabledNotificationResponse:
      example:
        nature: nature
        isEnabled: true
        channel: channel
        userUuid: userUuid
        uuid: uuid
      properties:
        channel:
          type: string
        isEnabled:
          type: boolean
        nature:
          type: string
        userUuid:
          type: string
        uuid:
          type: string
      required:
      - channel
      - isEnabled
      - nature
      - userUuid
      - uuid
      type: object
    schemas.GetEnabledNotificationListResponse:
      example:
        enabledNotifications:
        - nature: nature
          isEnabled: true
          channel: channel
          userUuid: userUuid
          uuid: uuid
        - nature: nature
          isEnabled: true
          channel: channel
          userUuid: userUuid
          uuid: uuid
      properties:
        enabledNotifications:
          items:
            $ref: '#/components/schemas/schemas.EnabledNotificationResponse'
          type: array
      required:
      - enabledNotifications
      type: object
    schemas.GetNotificationListResponse:
      example:
        size: 0
        notifications:
        - createdAt: createdAt
          nature: nature
          isRead: true
          userUuid: userUuid
          description: description
          uuid: uuid
          url: url
        - createdAt: createdAt
          nature: nature
          isRead: true
          userUuid: userUuid
          description: description
          uuid: uuid
          url: url
      properties:
        notifications:
          items:
            $ref: '#/components/schemas/schemas.NotificationResponse'
          type: array
        size:
          type: integer
      required:
      - notifications
      - size
      type: object
    schemas.NotificationResponse:
      example:
        createdAt: createdAt
        nature: nature
        isRead: true
        userUuid: userUuid
        description: description
        uuid: uuid
        url: url
      properties:
        createdAt:
          type: string
        description:
          type: string
        isRead:
          type: boolean
        nature:
          type: string
        url:
          type: string
        userUuid:
          type: string
        uuid:
          type: string
      required:
      - createdAt
      - description
      - isRead
      - nature
      - url
      - userUuid
      - uuid
      type: object
    schemas.UpdateEnabledNotificationPayload:
      properties:
        isEnabled:
          type: boolean
      required:
      - isEnabled
      type: object
    schemas.UpdateNotificationPayload:
      properties:
        isRead:
          type: boolean
      required:
      - isRead
      type: object
x-original-swagger-version: "2.0"
